apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-conf1000
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "vlan",
      "master": "eth2",
      "vlanId": 1000,
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.2.0/24",
        "rangeStart": "10.1.2.200",
        "rangeEnd": "10.1.2.216",
        "routes": [
          { "dst": "10.1.0.0/16", "gw":"10.1.2.1" }
        ],
        "gateway": "10.1.2.1"
      }
    }'