apiVersion: v1
kind: Pod
metadata:
  name: samplepod-vlan1001
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan-conf1001
spec:
  containers:
  - name: samplepod-vlan1001
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine