apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan1001
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth2.1001",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.3.0/24",
        "rangeStart": "10.1.3.200",
        "rangeEnd": "10.1.3.216",
        "routes": [
          { "dst": "10.1.0.0/16", "gw":"10.1.3.1" }
        ],
        "gateway": "10.1.3.1"
      }
    }'