apiVersion: v1
kind: Pod
metadata:
  name: vma3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "vlan1000",
              "ips": [ "10.1.2.200/24" ],
              "gateway": [ "10.1.2.1" ]
            }]'
spec:
  containers:
  - name: vma3
    image: alpine
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]