apiVersion: v1
kind: Pod
metadata:
  name: vmb3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "vlan1001",
              "ips": [ "10.1.3.200/24" ],
              "gateway": [ "10.1.3.1" ]
            }]'
spec:
  containers:
  - name: vmb3
    image: alpine
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]